import localFont from "next/font/local";
import Link from "next/link";
import "../globals.css";
import getDictionary from "./dictionaries/dictionary";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, ...rest }) {
  const dict = await getDictionary("bn");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-center gap-5 text-xl p-5 text-gray-300">
          <Link href={"/about"}>{dict.header.navLinks[0]}</Link>
          <Link href={"/blogs"}>{dict.header.navLinks[1]}</Link>
        </nav>
        <main className="max-w-3xl mx-auto"> {children}</main>
      </body>
    </html>
  );
}
